
<h1>Hello, Blog !</h1>

<a href="<?php echo $this->url('blog/add') ?>">Add</a>


<table class="table table-bordered table-hover">
    <thead>
    <th>ID</th><th>Title</th><th>Content</th><th>Action</th>
</thead>
<?php foreach ($this->data as $post): ?>
    <tr>
        <td><?= $post->getId() ?></td>
        <td><?= $post->getTitle() ?></td>
        <td><?= $post->getText() ?></td>
        <td><a href="<?php echo $this->url('blog/edit', array('id' => $post->getId())) ?>">Edit</a></td>
    </tr>
<?php endforeach ?>
</table>



