<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('ZF2 '. $this->translate('Zend Framework Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/js/jquery.min.js')
            ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>

    </head>
    <body>
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?php echo $this->url('home') ?>"><img src="<?php echo $this->basePath('img/zf2-logo.png') ?>" alt="Zend Framework 2"/>&nbsp;<?php echo $this->translate('Zend Framework Application') ?></a>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                        <li class="active"><a href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Home') ?></a></li>
                        
                        <li role="presentation" class="dropdown">
                            <a class="dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
                                <?php echo $this->translate('Album') ?> <span class="caret"></span>
                            </a>
                            <ul class="dropdown-menu">
                                <li><a href="<?php echo $this->url('album', array('action' => 'index' )) ?>"><?php echo $this->translate('Index Album') ?></a></li>
                                <li><a href="<?php echo $this->url('album', array('action' => 'list' )) ?>"><?php echo $this->translate('List Album') ?></a></li>
                                <li role="separator" class="divider"></li>
                                <li><a href="<?php echo $this->url('album', array('action' => 'add' )) ?>"><?php echo $this->translate('Add Album') ?></a></li>
                            </ul>
                        </li>
                        
                        <li role="presentation" class="dropdown">
                            <a class="dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
                                <?php echo $this->translate('News') ?> <span class="caret"></span>
                            </a>
                            <ul class="dropdown-menu">
                                <li><a href="<?php echo $this->url('news', array('action' => 'index')) ?>"><?php echo $this->translate('Index News') ?></a></li>
                                <li><a href="<?php echo $this->url('news', array('action' => 'list')) ?>"><?php echo $this->translate('List News') ?></a></li>
                                <li role="separator" class="divider"></li>
                                <li><a href="<?php echo $this->url('news', array('action' => 'add')) ?>"><?php echo $this->translate('Add News') ?></a></li>
                            </ul>
                        </li>
                        
                        <li><a href="<?php echo $this->url('blog') ?>"><?php echo $this->translate('Blog') ?></a></li>
                        
                    </ul>
                    
                    <ul class="nav navbar-nav navbar-right">
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" title="#" aria-expanded="false">
                                <i class="fa fa-star text-yellow"></i> <?php echo $this->translate('Settings') ?> <b class="caret"></b>
                            </a>
                            <ul class="dropdown-menu">
                                <li>
                                    <a href="#"><i class="fa fa-fw fa-paint-brush"></i> <?php echo $this->translate('Settings1') ?></a>
                                </li>
                                <li>
                                    <a href="#"><i class="fa fa-fw fa-shopping-cart"></i> <?php echo $this->translate('Settings2') ?></a>
                                </li>
                            </ul>
                        </li>
                        
                        <li>
                            <!-- https://github.com/ZF-Commons/ZfcUser/wiki/How-to-check-if-the-user-is-logged-in -->
                            <?php if(!$this->zfcUserIdentity()): ?>
                            <a href="<?php echo $this->url('zfcuser',array('action'=>'login'))?>"><i class="fa fa-fw fa-paint-brush"></i> <?php echo $this->translate('Login') ?></a>
                            <?php else: ?>
                            <a href="<?php echo $this->url('zfcuser/logout') ?>">
                                <i class="fa fa-fw fa-paint-brush"></i> 
                                    <?php echo $this->translate('Logout') ?>
                                    (<?php echo $this->zfcUserIdentity()->getUsername() ?>)
                            </a>
                            <?php endif?>
                        </li>

                    </ul>
                    
                    
                </div><!--/.nav-collapse -->
                
            </div>
        </nav>
        <div class="container">
            <?php echo $this->content; ?>
            <hr>
            <footer>
                <p>&copy; 2005 - <?php echo date('Y') ?> by Zend Technologies Ltd. <?php echo $this->translate('All rights reserved.') ?></p>
            </footer>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
