
<h1>Hello, Blog !</h1>

<a href="<?php echo $this->url('blog', array('action' => 'add')) ?>">Add</a>


<table class="table table-bordered table-hover">
    <thead>
    <th>ID</th><th>Title</th><th>Content</th><th>Action</th>
</thead>
<?php foreach ($this->data as $post): ?>
    <tr>
        <td><?= $post->getId() ?></td>
        <td><?= $post->getTitle() ?></td>
        <td><?= $post->getText() ?></td>
        <td>
            <a href="<?php echo $this->url('blog', array('action' => 'detail', 'id' => $post->getId())) ?>">Detail</a>
            <a href="<?php echo $this->url('blog', array('action' => 'edit', 'id' => $post->getId())) ?>">Edit</a>
            <a href="<?php echo $this->url('blog', array('action' => 'delete', 'id' => $post->getId())) ?>">Delete</a>
        </td>
    </tr>
<?php endforeach ?>
</table>



